/**
 * Wire
 * Copyright (C) 2016 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.waz.zclient.core.stores.stub;

import android.content.SharedPreferences;
import com.waz.zclient.core.stores.media.IMediaStore;
import java.lang.Override;
import java.lang.String;

/**
 * This class was AUTOGENERATED.
 *
 * All changes will be overwritten with the next build.
 */
public class StubMediaStore implements IMediaStore {
  @Override
  public void setCustomSoundUri(int resourceId, String uri) {
    ;
  }

  @Override
  public void playSound(int resourceId) {
    ;
  }

  @Override
  public void setCustomSoundUrisFromPreferences(SharedPreferences preferences) {
    ;
  }

  @Override
  public void stopSound(int resId) {
    ;
  }

  @Override
  public void tearDown() {
    ;
  }
}
